@startuml
class Resources {
    - {static} resourceMan : global::System.Resources.ResourceManager
    - {static} resourceCulture : global::System.Globalization.CultureInfo
    <<internal>> Resources()
    + {static} ResourceManager : global::System.Resources.ResourceManager <<get>>
    + {static} Culture : global::System.Globalization.CultureInfo <<get>> <<set>>
}
@enduml
