name: Belt Test Build

on:
  pull_request:
    branches:
    - master 
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run build
      shell: cmd
      run: ./build.cmd

    - name: Save Package
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./bin/**