@startuml Hymma.solidworks.addins
!include .\Core\AddinAttribute.puml
!include .\Core\AddinMaker.puml
!include .\Core\AddinUserInterface.puml
!include .\Core\IWrapSolidworksObject.puml
!include .\Core\OnConnectToSwEventArgs.puml
!include .\Helpers\AddinIcons.puml
!include .\Helpers\Counter.puml
!include .\Helpers\MaskedBitmap.puml
!include .\Properties\AssemblyInfo.puml
!include .\Properties\Resources.Designer.puml
!include .\UI\PopUpMenueItem.puml
!include .\Helpers\DotNet\RegisteryHelper.puml
!include .\obj\Debug\.NETFramework,Version=v4.6.1.AssemblyAttributes.puml
!include .\obj\Release\.NETFramework,Version=v4.6.1.AssemblyAttributes.puml
!include .\UI\Callout\CalloutModel.puml
!include .\UI\Callout\CalloutRow.puml
!include .\UI\Callout\OnRowValueChangedEventArgs.puml
!include .\UI\Callout\SolidworksCalloutHandler.puml
!include .\UI\ToolbarTabs\AddinCommandTab.puml
!include .\bin\Debug\Properties\Resources.Designer.puml
!include .\bin\Release\Properties\Resources.Designer.puml
!include .\Helpers\DotNet\Extensions\AssemblyExtensions.puml
!include .\Helpers\DotNet\Extensions\TypeExtensions.puml
!include .\UI\PropertyManagerPage\Core\PmpCloseReason.puml
!include .\UI\PropertyManagerPage\Core\PmpCursorStyles.puml
!include .\UI\PropertyManagerPage\Core\PmpEventHandler.puml
!include .\UI\PropertyManagerPage\Core\PmpFactoryBase.puml
!include .\UI\PropertyManagerPage\Core\PmpFactoryX64.puml
!include .\UI\PropertyManagerPage\Core\PmpOnKeyStrokeEventArgs .puml
!include .\UI\PropertyManagerPage\Core\PmpOptions.puml
!include .\UI\PropertyManagerPage\Core\PmpUiModel.puml
!include .\UI\PropertyManagerPage\PmpTab\PmpTab.puml
!include .\UI\ToolbarTabs\CommandGroup\AddinCommand.puml
!include .\UI\ToolbarTabs\CommandGroup\AddinCommandGroup.puml
!include .\UI\ToolbarTabs\CommandGroup\AddinCommandGroupBase.puml
!include .\UI\ToolbarTabs\CommandGroup\IAddinCommandGroup.puml
!include .\UI\PropertyManagerPage\PmpControls\Buttons\PmpBitmapButton.puml
!include .\UI\PropertyManagerPage\PmpControls\Buttons\PmpBitmapButtonCheckable.puml
!include .\UI\PropertyManagerPage\PmpControls\Buttons\PmpButton.puml
!include .\UI\PropertyManagerPage\PmpControls\Buttons\PmpButtonBase.puml
!include .\UI\PropertyManagerPage\PmpControls\Checkbox\PmpCheckBox.puml
!include .\UI\PropertyManagerPage\PmpControls\Checkbox\PmpCheckBoxCheckedEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\Combobox\ComboBoxStyles.puml
!include .\UI\PropertyManagerPage\PmpControls\Combobox\PmpComboBox.puml
!include .\UI\PropertyManagerPage\PmpControls\Core\IPmpControl.puml
!include .\UI\PropertyManagerPage\PmpControls\Core\PmpControl.puml
!include .\UI\PropertyManagerPage\PmpControls\Core\PmpTextBase.puml
!include .\UI\PropertyManagerPage\PmpControls\Group\PmpGroup.puml
!include .\UI\PropertyManagerPage\PmpControls\Group\PmpGroupCheckable.puml
!include .\UI\PropertyManagerPage\PmpControls\Image\PmpBitmap.puml
!include .\UI\PropertyManagerPage\PmpControls\Label\LabelStyles.puml
!include .\UI\PropertyManagerPage\PmpControls\Label\PmpLabel.puml
!include .\UI\PropertyManagerPage\PmpControls\Label\UnderLineStyles.puml
!include .\UI\PropertyManagerPage\PmpControls\ListBox\PmpListBox.puml
!include .\UI\PropertyManagerPage\PmpControls\NumberBox\PmpNumberBox.puml
!include .\UI\PropertyManagerPage\PmpControls\RadioButton\PmpRadioButton.puml
!include .\UI\PropertyManagerPage\PmpControls\SelectionBox\PmpSelectionBox.puml
!include .\UI\PropertyManagerPage\PmpControls\Slider\PmpSlider.puml
!include .\UI\PropertyManagerPage\PmpControls\Slider\SliderStyles.puml
!include .\UI\PropertyManagerPage\PmpControls\TextBox\PmpTextBox.puml
!include .\UI\PropertyManagerPage\PmpControls\WinForms\PmpWinForm.puml
!include .\UI\PropertyManagerPage\PmpControls\WinForms\PmpWinFormContoller.puml
!include .\UI\PropertyManagerPage\PmpControls\Wpf\PmpWpfHost.puml
!include .\UI\PropertyManagerPage\PmpControls\Wpf\WpfControlKeystrokePropagator.puml
!include .\UI\PropertyManagerPage\PmpControls\Buttons\Enums\BitmapButtons.puml
!include .\UI\PropertyManagerPage\PmpControls\Buttons\Enums\BtnSize.puml
!include .\UI\PropertyManagerPage\PmpControls\Core\Enums\ControlResizeStyles.puml
!include .\UI\PropertyManagerPage\PmpControls\Core\Events\PmpControlDisplayingEventArgs.puml
!include .\UI\PropertyManagerPage\PmpControls\Core\Events\PmpControlDisplayingEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\Label\Events\PmpLabelDisplayingEventArgs.puml
!include .\UI\PropertyManagerPage\PmpControls\Label\Events\PmpLabelDisplayingEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\ListBox\Enums\ListboxStyles.puml
!include .\UI\PropertyManagerPage\PmpControls\ListBox\Events\PmpListboxDisplayingEventArgs.puml
!include .\UI\PropertyManagerPage\PmpControls\ListBox\Events\PmpListboxDisplayingEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\ListBox\Events\PmpListboxRightClickedEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\ListBox\Events\PmpListboxSelectionChangedEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\NumberBox\Enums\NumberBoxStyles.puml
!include .\UI\PropertyManagerPage\PmpControls\NumberBox\Enums\NumberBoxUnit.puml
!include .\UI\PropertyManagerPage\PmpControls\NumberBox\Events\PmpNumberBoxDisplayingEventArgs.puml
!include .\UI\PropertyManagerPage\PmpControls\NumberBox\Events\PmpNumberBoxDisplayingEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\SelectionBox\Enums\SelectionBoxStyles.puml
!include .\UI\PropertyManagerPage\PmpControls\SelectionBox\Events\PmpSelectionBoxDisplayingEventArgs.puml
!include .\UI\PropertyManagerPage\PmpControls\SelectionBox\Events\PmpSelectionBoxEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\SelectionBox\Events\PmpSelectionBoxListChangedEventArgs.puml
!include .\UI\PropertyManagerPage\PmpControls\SelectionBox\Events\PmpSelectionBoxSelectionSubmittedEventArgs.puml
!include .\UI\PropertyManagerPage\PmpControls\SelectionBox\Events\PmpSelectionBoxSelectionSubmittedEventHandler.puml
!include .\UI\PropertyManagerPage\PmpControls\TextBox\Enums\TextBoxStyles.puml
@enduml
