@startuml
enum BitmapButtons {
    alongz= 1,
    angle= 2,
    auto_bal_circular= 3,
    auto_bal_left= 4,
    auto_bal_right= 5,
    auto_bal_square= 6,
    auto_bal_top= 7,
    diameter= 8,
    distance1= 9,
    distance2= 10,
    draft= 11,
    dve_but_cmark_bolt= 12,
    dve_but_cmark_linear= 13,
    dve_but_cmark_single= 14,
    leader_ang_above= 15,
    leader_ang_beside= 16,
    leader_hor_above= 17,
    leader_hor_beside= 18,
    leader_left= 19,
    leader_no= 20,
    leader_right= 21,
    leader_yes= 22,
    parallel= 23,
    perpendicular= 24,
    reverse_direction= 25,
    revision_circle= 26,
    revision_hexagon= 27,
    revision_square= 28,
    revision_triangle= 29,
    stackleft= 30,
    stackright= 31,
    stackup= 32,
    stack= 33,
    favorite_add= 34,
    favorite_delete= 35,
    favorite_save= 36,
    favorite_load= 37,
    dimension_set_default_attributes= 38,
}
@enduml
