@startuml
class OnRowValueChangedEventArgs {
    + OnRowValueChangedEventArgs(row:CalloutRow, text:string)
    + Row : CalloutRow <<get>> <<set>>
    + Value : string <<get>> <<set>>
}
EventArgs <|-- OnRowValueChangedEventArgs
@enduml
