using SolidWorks.Interop.sldworks;
using System;
using System.Drawing;

namespace Hymma.SolidTools.Addins
{
    /// <summary>
    /// a bitmap button for property manager page
    /// </summary>
    public class PmpBitmapButton : PmpControl<PropertyManagerPageBitmapButton>
    {

        /// <summary>
        /// generate a button with specified <see cref="Bitmap"/>
        /// </summary>
        public PmpBitmapButton(Bitmap bitmap) : base(SolidWorks.Interop.swconst.swPropertyManagerPageControlType_e.swControlType_BitmapButton)
        {
            SetBitmap(bitmap);
        }

        /// <summary>
        /// generate a button with standard icons
        /// </summary>
        /// <param name="standardIcon"></param>
        public PmpBitmapButton(BitmapButtons standardIcon) : base(SolidWorks.Interop.swconst.swPropertyManagerPageControlType_e.swControlType_BitmapButton)
        {
            SetBitmap(standardIcon);
        }

        /// <summary>
        /// assign a bitmap to this bitmap button
        /// Images should use: <br/>
        /// 256-color palette.<br/>
        ///margin of at least 3 blank pixels on all sides of the image because this is where the button borders are drawn; i.e., any pixels in the image in these 3 outer rows and columns of pixels are obscured by the button borders.
        /// </summary>
        /// <remarks>The rest of the images (selected, highlight regular, highlight selected, and disabled) for this button are automatically generated by SOLIDWORKS</remarks>
        /// <param name="bitmap"></param>
        public void SetBitmap(Bitmap bitmap)
        {
            IconGenerator.GetBtnBitmaps(bitmap, out string[] images, out string[] masked);
            SolidworksObject.SetBitmapsByName3(images, masked);
        }



        /// <summary>
        /// assign an icon to this bitmap button from a list of standard solidworks icons <br/>
        /// The not-clicked, clicked, and disabled states for the control are automatically set by the SOLIDWORKS application.
        /// </summary>
        /// <param name="standardIcon">standard icon as defined by <see cref="BitmapButtons"/></param>
        public void SetBitmap(BitmapButtons standardIcon)
        {
            SolidworksObject.SetStandardBitmaps((int)standardIcon);
        }

        /// <summary>
        /// fires when button is pressed
        /// </summary>
        public Action OnPress { get; set; }
    }

    /// <summary>
    /// a list of standard solidworks bitmaps 
    /// </summary>
    public enum BitmapButtons
    {
        /// <summary>
        /// along z icon
        /// </summary>
        alongz = 1,

        /// <summary>
        /// angle icon
        /// </summary>
        angle = 2,

        /// <summary>
        /// auto circular
        /// </summary>
        auto_bal_circular = 3,

        /// <summary>
        /// auto left
        /// </summary>
        auto_bal_left = 4,

        /// <summary>
        /// auto right
        /// </summary>
        auto_bal_right = 5,

        /// <summary>
        /// auto square
        /// </summary>
        auto_bal_square = 6,
        /// <summary>
        /// auto top
        /// </summary>
        auto_bal_top = 7,

        /// <summary>
        /// diameter
        /// </summary>
        diameter = 8,

        /// <summary>
        /// distance 1
        /// </summary>
        distance1 = 9,

        /// <summary>
        /// distance 2
        /// </summary>
        distance2 = 10,

        /// <summary>
        /// draft
        /// </summary>
        draft = 11,

        /// <summary>
        /// centermark bolt
        /// </summary>
        dve_but_cmark_bolt = 12,

        /// <summary>
        /// centermark linear
        /// </summary>
        dve_but_cmark_linear = 13,

        /// <summary>
        /// centermark single
        /// </summary>
        dve_but_cmark_single = 14,

        /// <summary>
        /// leader with anlge above
        /// </summary>
        leader_ang_above = 15,

        /// <summary>
        /// leader with angle beside
        /// </summary>
        leader_ang_beside = 16,

        /// <summary>
        /// leader horizontal above
        /// </summary>
        leader_hor_above = 17,

        /// <summary>
        /// leader horizontal beside
        /// </summary>
        leader_hor_beside = 18,

        /// <summary>
        /// leader left
        /// </summary>
        leader_left = 19,

        /// <summary>
        /// no leader
        /// </summary>
        leader_no = 20,

        /// <summary>
        /// leader right
        /// </summary>
        leader_right = 21,

        /// <summary>
        /// yes to leader
        /// </summary>
        leader_yes = 22,
        /// <summary>
        /// parallel
        /// </summary>
        parallel = 23,

        /// <summary>
        /// perpendicular
        /// </summary>
        perpendicular = 24,

        /// <summary>
        /// reverse direction
        /// </summary>
        reverse_direction = 25,

        /// <summary>
        /// revision circle
        /// </summary>
        revision_circle = 26,

        /// <summary>
        /// revision hexagon
        /// </summary>
        revision_hexagon = 27,

        /// <summary>
        /// revision square
        /// </summary>
        revision_square = 28,

        /// <summary>
        /// revision triangle
        /// </summary>
        revision_triangle = 29,

        /// <summary>
        /// stack left
        /// </summary>
        stackleft = 30,

        /// <summary>
        /// stack right
        /// </summary>
        stackright = 31,

        /// <summary>
        /// stack up
        /// </summary>
        stackup = 32,

        /// <summary>
        /// stack
        /// </summary>
        stack = 33,

        /// <summary>
        /// add to favorites
        /// </summary>
        favorite_add = 34,

        /// <summary>
        /// delete from favorites
        /// </summary>
        favorite_delete = 35,

        /// <summary>
        /// save favorites
        /// </summary>
        favorite_save = 36,

        /// <summary>
        /// load favorites
        /// </summary>
        favorite_load = 37,

        /// <summary>
        /// set default attributes to dimesnions
        /// </summary>
        dimension_set_default_attributes = 38
    }
}
